version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install bandit

  pre_build:
    commands:
      - echo "Running Security Scan..."
      - bandit -r . -f txt || true

  build:
    commands:
      - echo "Packaging application..."
      - zip -r function.zip .

artifacts:
  files:
    - function.zip
